apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: my-container
spec:
  selector:
    app: my-container
  ports:
    - protocol: TCP
      port: 80         # De poort waarop de service beschikbaar is
      targetPort: 80   # De poort waarop de applicatie in de pod draait
  type: ClusterIP      # Dit geeft aan dat het een ClusterIP service is (standaard)
